---
output:
  html_document: default
  pdf_document: default
---

```{r}
library(readr)
```


```{r}
DiamondDataComplete <-  read.csv(file.choose(), header=TRUE)
View(DiamondDataComplete)
```


```{r}
#install.packages('neuralnet')
library(neuralnet)
```


```{r}
#s <- sample(nrow(DiamondDataComplete), size=10000, #replace = FALSE, prob = NULL)
#diamonds.subset <- DiamondDataComplete[s, ]
#attach(diamonds.subset)
```


```{r}
#diamonds.subset$cut = factor(diamonds.subset$cut, levels = c('Fair','Good','Ideal', 'Premium','Very Good'), labels = c(0,1,2,3,4))
#diamonds.subset$color = factor(diamonds.subset$color, levels = c('D','E','F','G','H','I','J'), labels = c(0,1,2,3,4,5,6))
#diamonds.subset$clarity = factor(diamonds.subset$clarity, levels = c('I1','IF','SI1','SI2','VS1','VS2','VVS1','VVS2'), labels = c(0,1,2,3,4,5,6,7))

#View(diamonds.subset)
DiamondDataComplete$cut = factor(DiamondDataComplete$cut, levels = c('Fair','Good','Ideal', 'Premium','Very Good'), labels = c(0,1,2,3,4))
DiamondDataComplete$color = factor(DiamondDataComplete$color, levels = c('D','E','F','G','H','I','J'), labels = c(0,1,2,3,4,5,6))

DiamondDataComplete$clarity = factor(DiamondDataComplete$clarity, levels = c('I1','IF','SI1','SI2','VS1','VS2','VVS1','VVS2'), labels = c(0,1,2,3,4,5,6,7))
View(DiamondDataComplete)

```



```{r}
library(tidyverse)
#install.packages("GGally")
library(GGally)
```



```{r}
scale01 <- function(x){
  (x - min(x)) / (max(x) - min(x))
}
```



```{r}
DiamondDataComplete_nn <- DiamondDataComplete %>%
  mutate(carat = scale01(carat),
         table = scale01(table),
         depth = scale01(depth),
         price = scale01(price),
         x = scale01(x),
         y = scale01(y),
         z = scale01(z),
         cut = as.numeric(cut) - 1,
         color = as.numeric(color)- 1,
         clarity = as.numeric(clarity)-1) 


View(DiamondDataComplete_nn)
attach(DiamondDataComplete_nn)
```




```{r}
set.seed(123)

Diamond_NN1 <- neuralnet(cut ~ carat + table + depth + price + x + y + z + color + clarity, 
                         data = DiamondDataComplete_nn, 
                         linear.output = FALSE, 
                         likelihood = TRUE)
```



```{r}
plot(Diamond_NN1, rep = 'best')
```



```{R}
NN_5 <- neuralnet(cut ~ carat + table + depth + price + x + y + z + color + clarity, 
                       data = DiamondDataComplete_nn, 
                       linear.output = FALSE, 
                       likelihood = TRUE,
                       threshold = 0.01,
                       hidden = 5)
```





```{r}
plot(NN_5)
```

```{r}
NN_5$result.matrix
```


```{r}
#Testing the resulting output

library(dplyr)

testing <- subset(DiamondDataComplete_nn, select = c("carat","table","depth","price","x","y","z","color","clarity"))
head(testing)
```


```{r}
nn_results <- neuralnet::compute(NN_5, testing)
```

```{r}
results <- data.frame(actual = DiamondDataComplete_nn$cut, prediction = nn_results$net.result)
results
```


```{r}
accuracy <- sum(results$prediction)/length(DiamondDataComplete_nn$cut)*100
print(accuracy)

#99.99995   -- accuracy of neural network model hidden = 5
```

Now, comparing the three models, KNN, C50(decision tree) and ANN.

99.99 %  -- accuracy of neural network model hidden = 5 (ANN)

82.7% -- Accuracy of the c50 tree(Decision Tree)

65.7% -- Accuracy of KNN(K=1 gave the highest accuracy)


Among the three models, ANN gave the best accuracy of 99.99%





